<?php

function acf_featured_buttons_w_text()
{

    return array(
        array(
			'key' => 'field_63f52597ee5f5',
			'label' => 'Text + Featured Buttons',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
        array(
			'key' => 'field_63f525aaee5f6',
			'label' => 'Title',
			'name' => 'featured_buttons_w_text_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '*Max 30 Characters',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => 30,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63f525f6ee5f7',
			'label' => 'Text',
			'name' => 'featured_buttons_w_text_text',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '*Max 500 Characters',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => 500,
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_63f5261dee5f8',
			'label' => 'Links',
			'name' => 'featured_buttons_w_text_links',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 6,
			'collapsed' => '',
			'button_label' => 'Add Link',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_63f52638ee5f9',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'parent_repeater' => 'field_63f5261dee5f8',
				),
				array(
					'key' => 'field_63f52658ee5fa',
					'label' => 'Icon',
					'name' => 'icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'far',
						1 => 'fas',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
					'parent_repeater' => 'field_63f5261dee5f8',
				),
				array(
					'key' => 'field_63f52662ee5fb',
					'label' => 'Text',
					'name' => 'text',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 4,
					'placeholder' => '',
					'new_lines' => '',
					'parent_repeater' => 'field_63f5261dee5f8',
				),
			),
		),
    );
}
